batch_size: 8
burned_weight: 1.0
context_len: 6
data_dir: /home/pgmlvol/data/data_lite/
ddp_world_size: 1
depth: 4
early_stopping_min_delta: 0.0
early_stopping_patience: 25
embed_dim: 64
enable_amp: true
exclude_ignition: false
exclude_sourcemap: false
exp_dir: /home/pgmlvol/jjaiswal/pgml/FourCastNet/src/results
experiment_name: afno-relu-diffROS-str1-fut6-out3
fire_metrics_weight: 0.01
fuel_transport_weight: 0.01
future: 6
image_size: 296
log_interval: 100
logging_framework: mlflow
max_epochs: 25
max_gpu_utilization: 0.95
max_lr: 0.001
min_lr: 1.0e-05
mini_batch_size: 8
mixed_prec_dtype: bfloat16
mlflow_tracking_uri: /home/pgmlvol/mlflow2/
mse_weight: 1.0
num_blocks: 4
num_pred_frames: 3
num_workers: 2
out_channels: 1
patch_size: 4
physics_loss: false
physics_test: true
prefetch_factor: 2
ros_method: horizontal_average
run_id: 20251215_213138_lite_lr1e-3_lr1e-5_ctx6_emb64_blk4_ep25_sd43
seed: 43
teacher_forcing: false
temporal_patch_size: 3
temporal_stride: 1
test_sequences:
- 5
- 17
- 22
- 43
- 45
timestamp: '20251215_213138'
torch_compile: false
unburned_weight: 1.0
use_fuel_model: false
weight_decay: 0.01
which_data: data_lite
